import "../globals.css";
import Layout from "@/components/layout/Layout";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";
import { Cairo } from "next/font/google";
import ReduxProvider from "@/store/ReduxProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cairo = Cairo({
  subsets: ["arabic", "latin"],
});
export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={dir}>
      <body className={cairo.className}>
        <ReduxProvider>
          <NextIntlClientProvider messages={messages}>
            <Layout>{children}</Layout>
          </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
